[project]
name = "scrapper-api"
version = "0.1.0"
requires-python = ">=3.14,<4"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "fastapi>=0.136.1",
    "lxml>=6.1.0",
    "mysql-connector-python>=9.7.0",
    "pydantic>=2.13.4",
    "pydantic-settings>=2.14.2",
    "pymysql>=1.1.3",
    "requests>=2.33.1",
    "sqlalchemy>=2.0.49",
    "uvicorn[standard]>=0.46.0",
]

[dependency-groups]
dev = [
    "ruff>=0.15.12",
    "ty>=0.0.34",
]
